redis:
  image: redis

postgresql:
  image: postgres
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production

gitlab:
  image: gitlab/gitlab-ce
  links:
    - redis:redis
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment: 
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string

